### ISSUE TITLE
Me falta el fichero /tasas_academicas_2015.csv

### ISSUE THREAD

**Issue by JJ** [oslugr/datos-ugr#1]
De hecho, no hay en el repo ninguno que se llame así. Podría sustituirse por un URL directo, por ejemplo

**Comment by germaaan** [comment]
Por ahora estaba probando a procesar los CSV localmente, los he subido también aunque sea de forma temporal.

Ya he quitado los valores NA, pero ahora ignora las opciones de "scale_y_continuous" para tanto indicar la escala del "eje y" como las marcas en el mismo eje.
